### ISSUE TITLE
Old version need

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-erpnext#10]
Some customer want to use lower version of ERPNext, not all the latest version, could you support some important old version of ERPNext

**Comment by zengxc-1996** [comment]
```shell
14:46:36 watch.1          | Traceback (most recent call last):
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 68, in get_app_commands
14:46:36 watch.1          |     app_command_module = importlib.import_module(app + '.commands')
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib64/python3.6/importlib/__init__.py", line 126, in import_module
14:46:36 watch.1          |     return _bootstrap._gcd_import(name[level:], package, level)
14:46:36 watch.1          |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
14:46:36 watch.1          |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
14:46:36 watch.1          |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
14:46:36 watch.1          | ModuleNotFoundError: No module named 'erpnext.commands'
14:46:36 watch.1          | Traceback (most recent call last):
14:46:36 watch.1          |   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
14:46:36 watch.1          |     "__main__", mod_spec)
14:46:36 watch.1          |   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
14:46:36 watch.1          |     exec(code, run_globals)
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
14:46:36 watch.1          |     main()
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
14:46:36 watch.1          |     click.Group(commands=commands)(prog_name='bench')
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
14:46:36 watch.1          |     return self.main(*args, **kwargs)
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
14:46:36 watch.1          |     rv = self.invoke(ctx)
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
14:46:36 watch.1          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
14:46:36 watch.1          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
14:46:36 watch.1          |     return ctx.invoke(self.callback, **ctx.params)
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
14:46:36 watch.1          |     return callback(*args, **kwargs)
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/commands/utils.py", line 36, in watch
14:46:36 watch.1          |     frappe.init('')
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/__init__.py", line 175, in init
14:46:36 watch.1          |     setup_module_map()
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/__init__.py", line 1008, in setup_module_map
14:46:36 watch.1          |     for module in get_module_list(app):
14:46:36 watch.1          |   File "/data/wwwroot/frappe-bench/apps/frappe/frappe/__init__.py", line 878, in get_module_list
14:46:36 watch.1          |     return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
14:46:36 watch.1          | AttributeError: module 'erpnext' has no attribute '__file__'
```
erpnext11  start error

**Comment by qiaofeng1227** [comment]
version 11 parameter is different from 12

Done
